apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: compilehub
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: compilehub
data:
  provider.yaml: |-
    apiVersion: 1
    providers:
      - name: 'CompileHub Dashboards'
        orgId: 1
        folder: 'CompileHub Telemetry'
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: compilehub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.0.3
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: "/var/lib/grafana/dashboards/compilehub-dashboard.json"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          volumeMounts:
            - name: datasources-volume
              mountPath: /etc/grafana/provisioning/datasources
            - name: provider-volume
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards-json-volume
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: datasources-volume
          configMap:
            name: grafana-datasources
        - name: provider-volume
          configMap:
            name: grafana-dashboard-provider
        - name: dashboards-json-volume
          configMap:
            name: compilehub-dashboard-json
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: compilehub
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
