[web_servers]
compilehub-ec2  ansible_host=32.199.183.159  ansible_user=ec2-user  ansible_ssh_private_key_file=../k2sh.pem

[web_servers:vars]
ansible_python_interpreter=/usr/bin/python3
app_name=compilehub
app_dir=/home/ec2-user/compilehub
node_version=20
