global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'compilehub-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['compilehub-server:5000']
        labels:
          service: 'compilehub-api'
          environment: 'local'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
