apiVersion: v1
kind: Service
metadata:
  name: compilehub-client-service
  namespace: compilehub
  labels:
    app: compilehub-client
spec:
  type: ClusterIP
  selector:
    app: compilehub-client
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
